Support text log
simplybusiness/twiglet-ruby-stale pull request #13
Opened 2020-06-09 11:21 UTC by punitcse

# What
- Support text logging in twiglet by converting text into a ECS format.
- Add few test to support that.
- some refactoring.

# Why
So we can save use the twiglet for libraries which are using text logging.

@simplybusiness/application-tooling

2020-06-09 12:16 UTC, sleepyfox requested changes

2020-06-09 12:16 UTC, sleepyfox commented on test/logger_test.rb
> +    it 'should log mandatory attributes' do
I'm not seeing what the difference is between the before and after of the git diff here.

2020-06-09 12:16 UTC, sleepyfox commented on lib/twiglet/logger.rb
> +      case message
Can I suggest that we subclass Logger here to have an ObjectLogger and a StringLogger, and for the ObjectLogger to be the default and to behave as it currently does, but the StringLogger to have the new functionality?

2020-06-09 12:40 UTC, punitcse commented on test/logger_test.rb
> +    it 'should log mandatory attributes' do
I have added a describe block before 'JSON Loggig' and `text logging` to separate the concerns

2020-06-09 12:43 UTC, punitcse commented on lib/twiglet/logger.rb
> +      case message
Sure, you suggested that yesterday I missed that. My bad.

I have few questions lets pair on this when you get some time.

2020-06-09 13:58 UTC, moltenice commented on lib/twiglet/logger.rb
>      def log(level:, message:)
I think if we are making this change we should try and implement EVERY method interface from BOTH Rails and Ruby's internal logging but implement it to be ECS compliant to ensure most libraries trying to log will work with Twiglet.

2020-06-09 15:54 UTC, sleepyfox commented
I disagree, just the ones that are actually used or we'll have a
wasteground of dead methods.

On Tue, 9 Jun 2020 at 14:59, Karan Shah <notifications@github.com> wrote:
>
> @moltenice commented on this pull request.
>
> ________________________________
>
> In lib/twiglet/logger.rb:
>
> > @@ -65,12 +65,18 @@ def with(default_properties)
>      private
>
>      def log(level:, message:)
>
> I think if we are making this change we should try and implement EVERY method interface from BOTH Rails and Ruby's internal logging but implement it to be ECS compliant to ensure most libraries trying to log will work with Twiglet.
>
> —
> You are receiving this because you are on a team that was mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.

2020-06-10 08:59 UTC, punitcse commented on lib/twiglet/logger.rb
>      def log(level:, message:)
The only fear I have and as @sleepyfox said lot of unnecessary methods. 
I will try and see if we can use the ruby formatter in some ways, if I get some time today.

2020-06-10 11:07 UTC, sleepyfox approved these changes
:pear:

2020-06-10 11:08 UTC, merged