[SPIKE] - Use Ruby Formatter
simplybusiness/twiglet-ruby-stale pull request #15
Opened 2020-06-11 11:57 UTC by punitcse

# What
- Inherit all the functionality of Ruby formatter
- add block functionality by default.

# Why
- We have seen number of cases where we have to fix the twiglet logger on case by case like for text support.
- this will use extend the ruby formatter so all functionality will come by default and we dont need to worry about any internal library using any code.

# Future direction
Most of the tests are passing but 3 tests are failing which are related with the `add` method. We need to fix this.
This PR need some cleanup and naming changes (rubocop).

2020-06-11 13:17 UTC, sleepyfox requested changes

2020-06-11 13:17 UTC, sleepyfox commented on test/logger_test.rb
> +                                  output: @buffer).logging
the `.logging` on the end is a bit ugly - can we roll this up into the constructor?

2020-06-11 13:17 UTC, sleepyfox commented on test/logger_test.rb
> +    { method: :debug, level: 'DEBUG' },
These levels are no longer compliant with the original spec. What's the rationale here?

2020-06-11 13:17 UTC, sleepyfox commented on test/logger_test.rb
> +      # assert_equal 'Guinea pigs arrived', log[:message]
This shouldn't be commented out.

2020-06-11 13:17 UTC, sleepyfox commented on test/logger_test.rb
> +          level: 'ERROR'
ECS spec calls for all output to be lowercase.

2020-06-11 13:20 UTC, sleepyfox commented on lib/twiglet/logger.rb
> -        add_stack_trace(error_fields, error)
Does this still correctly produce a stack trace as per the spec (an Array of Strings)?

2020-06-11 15:15 UTC, punitcse commented on lib/twiglet/logger.rb
> -        add_stack_trace(error_fields, error)
No the error spec was failing. I need to fix this.

2020-06-11 15:16 UTC, punitcse commented on test/logger_test.rb
> +                                  output: @buffer).logging
yep! My idea was to first make it working and then deal with this. Its now fixed.

2020-06-11 15:16 UTC, punitcse commented on test/logger_test.rb
> +    { method: :debug, level: 'DEBUG' },
fixed.

2020-06-11 15:16 UTC, punitcse commented on test/logger_test.rb
> +      # assert_equal 'Guinea pigs arrived', log[:message]
done

2020-06-11 15:16 UTC, punitcse commented on test/logger_test.rb
> +          level: 'ERROR'
done

2020-06-12 09:44 UTC, punitcse commented on lib/twiglet/logger.rb
> -        add_stack_trace(error_fields, error)
fixed

2020-06-12 10:00 UTC, sleepyfox approved these changes
Looking much better.

2020-06-23 15:38 UTC, doryphores commented on lib/twiglet/logger.rb
> +      def call(severity, _time, _progname, msg)
This has probably been answered elsewhere but what's the reason behind not using `time` here and using the `now` lambda instead?

2020-06-23 15:56 UTC, rifkinni commented
https://github.com/simplybusiness/twiglet-ruby/pull/15#discussion_r444320262

@doryphores I think this is just a relic of the original implementation, feel free to open up a PR to update!

2020-06-23 16:20 UTC, doryphores commented
Should this PR be closed then?

2020-06-23 16:23 UTC, punitcse commented
> Should this PR be closed then?

Yes @rifkinni has done the implementation so we can close this one.

2020-06-23 16:23 UTC, closed without merging

2020-06-23 16:43 UTC, sleepyfox commented on lib/twiglet/logger.rb
> +      def call(severity, _time, _progname, msg)
Constructor injection. This is so that you can simply stub `now` in the tests. It would also allow for different datestamp formatters to be used, should that become necessary by decoupling the side-effectful system time utility from the logger, allowing the logger to have referential transparency.