Twiglet Ruby initialisation improvement
simplybusiness/twiglet-ruby-stale pull request #5
Opened 2020-06-02 13:27 UTC by moltenice

Improve ease of creating a new Twiglet object in most cases

2020-06-02 13:29 UTC, rifkinni commented on README.md
> +logger = Twiglet::Logger.new('petshop') # 'petshop' is the service name
At least for the documentation, can we call this `'service name'` and ditch the comment?

2020-06-02 13:30 UTC, punitcse reviewed
~You also want to update the gemspec~ Ignore.Now see version file

2020-06-02 13:31 UTC, rifkinni commented on lib/twiglet/logger.rb
> +        unless @service_name.is_a?(String) && !@service_name.strip.empty?
use `present?` instead of `!empty?` (generally, you rarely want to use the `!` operator in ruby, because there is almost always a utility method available instead!

2020-06-02 13:37 UTC, rifkinni reviewed
👍 a few nitpicks but I'm a big fan of the change overall!

2020-06-02 13:37 UTC, rifkinni commented on lib/twiglet/logger.rb
> +      total_message = deep_merge(total_message, to_nested(message))
I generally like to avoid variable reassignment - I'm pretty sure you can chain these calls!

2020-06-02 13:37 UTC, rifkinni commented on lib/twiglet/logger.rb
> +      scoped_properties: {},
Not sure I'm sold on the name `scoped_properties`, just because it is a little bit long and still isn't super clear to me without referring to the docs. Something as simple as `args` might be more conventional? I don't feel too strongly on this one, though!

2020-06-02 13:39 UTC, sleepyfox commented on README.md
> +logger = Twiglet::Logger.new('petshop') # 'petshop' is the service name
Personally I'm not a big fan of examples with `my name`, YMMV

2020-06-02 13:40 UTC, sleepyfox commented on lib/twiglet/logger.rb
> +      total_message = deep_merge(total_message, to_nested(message))
deep_merge is a procedure, so without monkey_patching Hash, no chaining. Possibly use Compose or similar?

2020-06-02 13:41 UTC, sleepyfox commented on lib/twiglet/logger.rb
> +      scoped_properties: {},
It isn't args though, it's `things that will also get shoved into the message hash`, happy to take offers of better names!

2020-06-02 13:41 UTC, sleepyfox commented on README.md
> +logger = Twiglet::Logger.new('petshop') # 'petshop' is the service name
OK

2020-06-02 13:42 UTC, sleepyfox commented on README.md
> +Lastly, you can provide another optional keyword argument called `now`, which should be a function returning a `Time` object.
```suggestion
Lastly, you can provide another optional keyword argument called `now`, which should be a function returning a `Time` string in ISO8601 format.
```

2020-06-02 13:45 UTC, moltenice commented on README.md
> +logger = Twiglet::Logger.new('petshop') # 'petshop' is the service name
Oh good shout! I agree we don't need a comment here!

2020-06-02 13:46 UTC, sleepyfox commented on test/logger_test.rb
> +    @logger.error({message: 'Out of pets exception'})
Is this personal preference or Rubocop?

2020-06-02 13:48 UTC, moltenice commented on lib/twiglet/logger.rb
> +      scoped_properties: {},
`default_properties`?

2020-06-02 13:49 UTC, moltenice commented on lib/twiglet/logger.rb
> +        unless @service_name.is_a?(String) && !@service_name.strip.empty?
This bit of code was always present and not updated by me! But good should I will update this.

2020-06-02 13:50 UTC, moltenice commented on lib/twiglet/logger.rb
> +      total_message = deep_merge(total_message, to_nested(message))
Any idea how we can do this without reassignment?

2020-06-02 14:00 UTC, rifkinni commented on lib/twiglet/logger.rb
> +      scoped_properties: {},
+1 I like `default_properties`

2020-06-02 14:29 UTC, moltenice commented on README.md
> +logger = Twiglet::Logger.new('petshop') # 'petshop' is the service name
Done

2020-06-02 14:37 UTC, moltenice commented on lib/twiglet/logger.rb
> +        unless @service_name.is_a?(String) && !@service_name.strip.empty?
Not going to be able to change this since apparently it's a Rails thing as discussed 😢

2020-06-02 14:39 UTC, moltenice commented on test/logger_test.rb
> +    @logger.error({message: 'Out of pets exception'})
This is Ctrl + Alt + L in RubyMine. Happy to tell it it's wrong if you feel strongly about keeping the spaces :P

2020-06-02 16:00 UTC, punitcse commented on test/logger_test.rb
> +    @logger.error({message: 'Out of pets exception'})
rubocop passed so definetly it does not object by default.

2020-06-02 16:12 UTC, moltenice commented on lib/twiglet/logger.rb
> +      scoped_properties: {},
Done!

2020-06-02 16:38 UTC, sleepyfox commented on lib/twiglet/logger.rb
> +      total_message = deep_merge(total_message, to_nested(message))
I'd suggest that the idiomatic Ruby thing here is to make a subclass of Hash that has the deep_merge method (or just monkey patch Hash) and then use something like the below: 

```suggestion
      total_message = total_message.deep_merge(to_nested@default_properties())
                                   .deep_merge(to_nested(message))
```

2020-06-03 09:58 UTC, moltenice commented on lib/twiglet/logger.rb
> +      total_message = deep_merge(total_message, to_nested(message))
Done!

2020-06-03 11:26 UTC, sleepyfox requested changes

2020-06-03 11:26 UTC, sleepyfox commented on lib/twiglet/logger.rb
> +                     .to_json
Best to rename total_message to just message at this point

2020-06-03 12:44 UTC, moltenice commented on lib/twiglet/logger.rb
> +                     .to_json
`message` already exists. I have changed to `base_message` as I agree `total_message` doesn't really make sense here.

2020-06-03 13:03 UTC, sleepyfox approved these changes
:shipit:

2020-06-03 15:02 UTC, merged